using System.Text;
using YamlDotNet.Serialization;
using YamlDotNet.Serialization.NamingConventions;

var arguments = ArgsParser.Parse(args);
if (!arguments.IsValid)
{
    Console.Error.WriteLine("Usage: pcd-cli --contract <path> --configs <path> [--output <path>]");
    return 1;
}

var contractText = await File.ReadAllTextAsync(arguments.ContractPath);
var deserializer = new DeserializerBuilder()
    .WithNamingConvention(UnderscoredNamingConvention.Instance)
    .IgnoreUnmatchedProperties()
    .Build();
var contract = deserializer.Deserialize<GraphQlContract>(contractText);
contract ??= new GraphQlContract();

var configFiles = Directory.EnumerateFiles(arguments.ConfigDirectory, "*.yaml", SearchOption.AllDirectories)
    .Concat(Directory.EnumerateFiles(arguments.ConfigDirectory, "*.yml", SearchOption.AllDirectories))
    .Distinct()
    .ToList();

if (configFiles.Count == 0)
{
    Console.Error.WriteLine($"No configs found in {arguments.ConfigDirectory}.");
    return 1;
}

Directory.CreateDirectory(arguments.OutputDirectory);

foreach (var configPath in configFiles)
{
    var configText = await File.ReadAllTextAsync(configPath);
    var operation = deserializer.Deserialize<GraphQlOperationConfig>(configText) ?? new GraphQlOperationConfig();
    if (string.IsNullOrWhiteSpace(operation.Method))
    {
        Console.Error.WriteLine($"Skipping config {configPath} because 'method' is missing.");
        continue;
    }

    var fileName = operation.FileName ?? $"{operation.Method}.gql.cs";
    var outputPath = Path.Combine(arguments.OutputDirectory, fileName);

    var builder = new StringBuilder();
    builder.AppendLine("// <auto-generated>");
    builder.AppendLine("// Generated via Motion-First PCD CLI. Do not edit by hand.");
    builder.AppendLine("// </auto-generated>");
    builder.AppendLine();

    foreach (var @using in contract.GetUsings())
    {
        builder.AppendLine($"using {@using};");
    }

    builder.AppendLine();
    builder.AppendLine($"namespace {contract.Runtime.Namespace};");
    builder.AppendLine();
    builder.AppendLine($"public partial class {contract.Shape.RootType}");
    builder.AppendLine("{");

    var summary = string.IsNullOrWhiteSpace(operation.Summary)
        ? $"Executes the {operation.Method} GraphQL {operation.Operation}."
        : operation.Summary;
    builder.AppendLine($"    /// <summary>{summary}</summary>");
    if (!string.IsNullOrWhiteSpace(operation.Description))
    {
        builder.AppendLine($"    [GraphQLDescription(\"{operation.Description}\")] ");
    }

    builder.AppendLine($@"    public async Task<{contract.Response.WrapperType}<{operation.ResultType}>> {operation.Method}(
        {operation.InputType} input,
        [Service] {contract.Shape.EntryService} entry,
        CancellationToken {contract.Shape.CancellationTokenParameter})");
    builder.AppendLine("    {");
    builder.AppendLine($"        var result = await entry.{operation.EntryMethod}(input, {contract.Shape.CancellationTokenParameter});");
    builder.AppendLine($"        return {contract.Response.WrapperType}<{operation.ResultType}>.{contract.Response.HelperMethod}(\n            result,\n            {operation.SuccessPayload});");
    builder.AppendLine("    }");

    builder.AppendLine("}");

    await File.WriteAllTextAsync(outputPath, builder.ToString());
    Console.WriteLine($"Generated {outputPath}");
}

return 0;

internal record ArgsParser(string ContractPath, string ConfigDirectory, string OutputDirectory)
{
    public bool IsValid => !string.IsNullOrWhiteSpace(ContractPath)
                           && !string.IsNullOrWhiteSpace(ConfigDirectory)
                           && !string.IsNullOrWhiteSpace(OutputDirectory);

    public static ArgsParser Parse(string[] args)
    {
        string? contract = null;
        string? configs = null;
        string? output = null;

        for (var i = 0; i < args.Length; i++)
        {
            var current = args[i];
            switch (current)
            {
                case "--contract":
                    contract = i + 1 < args.Length ? args[++i] : contract;
                    break;
                case "--configs":
                    configs = i + 1 < args.Length ? args[++i] : configs;
                    break;
                case "--output":
                    output = i + 1 < args.Length ? args[++i] : output;
                    break;
            }
        }

        output ??= Path.Combine("src", "Api", "GraphQL", "Generated");

        return new ArgsParser(contract ?? string.Empty, configs ?? string.Empty, output);
    }
}

internal sealed class GraphQlContract
{
    public RuntimeSection Runtime { get; init; } = new();
    public ShapeSection Shape { get; init; } = new();
    public ResponseSection Response { get; init; } = new();
    public List<string> Usings { get; init; } = new();

    public IEnumerable<string> GetUsings()
    {
        if (Usings.Count > 0)
        {
            return Usings;
        }

        return new[]
        {
            "System",
            "System.Threading",
            "System.Threading.Tasks",
            "Application.Common.Exceptions",
            "Application.Student",
            "Application.Student.Inputs",
            "HotChocolate"
        };
    }

    internal sealed class RuntimeSection
    {
        public string Namespace { get; init; } = "Api";
    }

    internal sealed class ShapeSection
    {
        public string RootType { get; init; } = "Mutation";
        public string EntryService { get; init; } = "StudentOperationsEntry";
        public string CancellationTokenParameter { get; init; } = "cancellationToken";
    }

    internal sealed class ResponseSection
    {
        public string WrapperType { get; init; } = "ResponseMessage";
        public string HelperMethod { get; init; } = "ToResponse";
    }
}

internal sealed class GraphQlOperationConfig
{
    public string Operation { get; init; } = "mutation";
    public string Method { get; init; } = string.Empty;
    public string Summary { get; init; } = string.Empty;
    public string Description { get; init; } = string.Empty;
    public string InputType { get; init; } = string.Empty;
    public string ResultType { get; init; } = "Guid";
    public string EntryMethod { get; init; } = string.Empty;
    public string SuccessPayload { get; init; } = "result.IsSuccess ? result.Value : Guid.Empty";
    public string? FileName { get; init; }
}
